version=1.0.0
group=io.github.ragin-lundf

javaVersion=25

# set the flag in the gradle.properties
useMavenLocal=false

kotlin.incremental=true

org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Xss256k -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:+UseCompressedOops -XX:+AlwaysPreTouch -XX:+TieredCompilation -XX:+UseStringDeduplication
#org.gradle.logging.level=quiet

# org.gradle.warning.mode=(all,none,summary)
org.gradle.warning.mode=all
org.gradle.java.installations.auto-download=false
kapt.include.compile.classpath=false
